###############################################################################
#  In settings.py:
#       DATABASES = {
#            'default': {
#                'ENGINE': 'django.db.backends.mysql',
#                'HOST': 'mysql',
#                {   ...
#            }
#        }
#
#  In PyCharm configurations:
#       Host: 0.0.0.0 - Port: 8000
#       Python interpreter: Select the docker ...
###############################################################################
version: "3.1"



services:

    django:
      build: app
      container_name: ${PROJECT_NAME}-django
      command: .entrypoint.sh
      env_file:
       - .env
      volumes:
        - ./app:/app
        - static_volume:/static
      expose:
         - 8000
      depends_on:
        - mysql

    mysql:
      image: mysql:5.6
      container_name: ${PROJECT_NAME}-mysql
      environment:
       - MYSQL_ROOT_PASSWORD=root
      volumes:
        - mysql-data:/var/lib/mysql
      ports:
        - "8307:3306"


    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: ${PROJECT_NAME}-phpmyadmin
      environment:
          - PMA_HOST=cowrywise-mysql
          -  COMPOSE_HTTP_TIMEOUT=180
      restart: always
      ports:
             - 8083:80
      volumes:
             - /session

    nginx:
      build: ./nginx
      container_name: ${PROJECT_NAME}-nginx
      volumes:
           - static_volume:/static
      ports:
           - 8000:8000
      depends_on:
          - django


volumes:
  mysql-data:
  static_volume:

