# Generated by Django 2.2.3 on 2019-08-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0002_auto_20190731_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='groupinstance',
            old_name='created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='groupinstance',
            old_name='updated_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='group',
            name='is_searchable',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='group',
            name='slot',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='groupinstance',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
