# Generated by Django 2.2.3 on 2019-08-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0003_auto_20190801_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='slot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupinstance',
            name='contribution',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
