# Generated by Django 2.2.3 on 2019-08-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0009_auto_20190813_0514'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='group',
        #     name='slug',
        # ),
    ]
