# Generated by Django 2.2.3 on 2019-08-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0010_remove_group_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slot',
        ),
        migrations.AddField(
            model_name='group',
            name='share_link',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
