# Generated by Django 2.2.3 on 2019-08-27 06:10

from django.db import migrations, models
import esusu.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0011_auto_20190815_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Unique Verification UUID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='share_link',
            field=models.CharField(blank=True, default=esusu.models.Group.create_link, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='contribution',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
