# Generated by Django 2.2.3 on 2019-09-10 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import esusu.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0013_auto_20190827_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text="User's Account Number", primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=500000, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='contribution',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='pay_freq',
            field=models.CharField(default='D', max_length=1, verbose_name='Payment Frequency'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.UUIDField(default=uuid.uuid4, help_text="User's Account Number", primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('receipt_no', models.CharField(default=esusu.models.Transaction.generate_reference, max_length=15)),
                ('trans_type', models.CharField(default='test', max_length=15)),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(default='Success', max_length=100)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='esusu.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SavingPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodic_amount', models.DecimalField(decimal_places=2, default=500000, max_digits=14)),
                ('frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, verbose_name='Frequency')),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Paused')], max_length=1, verbose_name='Status')),
                ('day_of_month', models.IntegerField(null=True, verbose_name='Day')),
                ('time', models.TimeField(verbose_name='Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savingspref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaveMoneyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='time')),
                ('frequency', models.CharField(max_length=1, null=True, verbose_name='Frequency')),
                ('status', models.IntegerField(choices=[('1', 'YES'), ('0', 'NO')], max_length=1, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
