# Generated by Django 2.2.3 on 2019-09-02 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import esusu.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0013_auto_20190827_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, help_text="User's Account Number", primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=50000, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.UUIDField(default=uuid.uuid4, help_text="User's Account Number", primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('receipt_no', models.CharField(default=esusu.models.Transaction.generate_reference, max_length=15)),
                ('trans_type', models.CharField(default='test', max_length=15)),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(max_length=100)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='esusu.Account')),
            ],
        ),
    ]
