# Generated by Django 2.2.3 on 2019-09-02 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0014_account_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_freq',
            field=models.CharField(default='D', max_length=1, verbose_name='Payment Frequency'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=14),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
