# Generated by Django 2.2.3 on 2019-09-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0014_auto_20190910_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepreference',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Pause')], max_length=1, verbose_name='Status'),
        ),
    ]
