# Generated by Django 2.2.3 on 2019-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0015_auto_20190902_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
