# Generated by Django 2.2.3 on 2019-09-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0017_auto_20190902_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='response',
            field=models.TextField(default='Sucess', max_length=100),
        ),
    ]
