# Generated by Django 2.2.3 on 2019-09-04 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0018_auto_20190904_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodic_amount', models.DecimalField(decimal_places=2, default=500000, max_digits=14)),
                ('frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, verbose_name='Frequency')),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Paused')], max_length=1, verbose_name='Status')),
                ('day_of_month', models.IntegerField(null=True, verbose_name='Month')),
                ('time', models.TimeField(verbose_name='Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savingspref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
