# Generated by Django 2.2.3 on 2019-09-04 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0019_savingpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savingspref', to=settings.AUTH_USER_MODEL),
        ),
    ]
