# Generated by Django 2.2.3 on 2019-09-08 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0020_auto_20190904_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingpreference',
            name='day_of_month',
            field=models.IntegerField(null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='response',
            field=models.TextField(default='Success', max_length=100),
        ),
        migrations.CreateModel(
            name='SaveMoneyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='time')),
                ('status', models.IntegerField(choices=[('1', 'YES'), ('0', 'NO')], max_length=1, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
