# Generated by Django 2.2.3 on 2019-09-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0021_auto_20190908_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='savemoneylog',
            name='frequency',
            field=models.CharField(max_length=1, null=True, verbose_name='Frequency'),
        ),
    ]
